# Generated by Django 3.2.15 on 2022-08-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220829_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer', to='core.peer'),
        ),
        migrations.CreateModel(
            name='TemporaryTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.validator')),
                ('trans', models.ManyToManyField(to='core.Transaction')),
            ],
        ),
    ]
